export const defaultContent = {
  heroBadge: 'Universal Modular Power System · Patent Pending',
  heroHeadline: 'One System,',
  heroHeadlineAccent: 'Endless Possibilities.',
  heroSubtext: 'A complete rethink of internal combustion — delivering both vehicle propulsion and building energy from a single, multi-fuel opposed-piston platform.',
  heroStats: [
    { value: '100%', label: 'Hydraulic Output' },
    { value: 'Multi-Fuel', label: 'On The Fly' },
    { value: 'HCCI', label: 'Combustion Mode' },
    { value: 'CHP', label: 'Combined Heat & Power' },
  ],
  howTitle: 'An engine designed from first principles',
  howDescription: 'The UniMod uses an opposed-piston configuration — two pistons per cylinder moving in opposite directions — eliminating cylinder heads and dramatically reducing heat loss. The result: higher thermal efficiency and fewer moving parts.',
  howPoints: [
    { title: 'Opposed-Piston Architecture', description: 'Two pistons share a single combustion chamber, reducing surface area and thermal losses vs. conventional engines.' },
    { title: 'HCCI Combustion', description: 'Homogeneous Charge Compression Ignition achieves diesel-like efficiency on gasoline — with significantly lower NOx emissions.' },
    { title: 'Hydraulic Power Output', description: '90% of output delivered as hydraulic pressure — ideal for both vehicle drive systems and stationary power generation.' },
  ],
  techTitle: 'Technology Breakthroughs',
  techSubtitle: 'Built for a world that demands more from every drop of fuel',
  techFeatures: [
    { icon: '⚡', title: 'Smart 90/10 Power Split', description: 'Outputs 90% of power hydraulically and 10% electrically — optimized for hybrid drivetrain and stationary applications simultaneously.' },
    { icon: '🔄', title: 'Regenerative Hydraulics', description: 'Hydraulic accumulator captures braking energy and stores it for later release, delivering regenerative braking without complex electrical inverters.' },
    { icon: '🎚️', title: 'Variable Compression Ratio', description: 'Dynamically adjusts compression to match fuel quality and load conditions — enabling multi-fuel operation with peak efficiency across the board.' },
    { icon: '⛽', title: 'Multi-Fuel Versatility', description: 'Runs on natural gas, gasoline, or diesel without hardware changes. Future-proof against fuel availability and price volatility.' },
    { icon: '🏗️', title: 'Modular Design', description: 'Scalable and stackable architecture. From light vehicles to industrial buildings, the same core engine scales to meet any power demand.' },
    { icon: '🌿', title: 'Lower Emissions', description: 'HCCI combustion produces dramatically lower NOx and particulates vs. conventional spark-ignition engines at equivalent power output.' },
  ],
  appsTitle: 'One platform, two markets',
  appsSubtitle: "The UniMod's modular architecture makes it equally at home under the hood of a work vehicle or powering a commercial building.",
  applications: [
    {
      title: 'Vehicle Propulsion',
      description: 'Drop-in hydraulic hybrid drivetrain for trucks, buses, and off-road equipment. Hydraulic accumulators replace complex battery packs for regenerative braking — delivering commercial-grade durability with zero battery degradation.',
      tags: ['Trucks', 'Buses', 'Off-Road', 'Fleet'],
    },
    {
      title: 'Building Energy Systems',
      description: 'Simultaneous electrical and mechanical power for HVAC, lighting, and process loads. On-site generation with multi-fuel flexibility makes it ideal for hospitals, data centers, and microgrids needing resilient power.',
      tags: ['Microgrids', 'Data Centers', 'HVAC', 'Hospitals'],
    },
  ],
  companyTitle: 'Founded on a fundamental question',
  companyDescription: 'Paul and Matthew Borner founded Unimod Motors with a single goal: to ask whether the internal combustion engine\'s fundamental architecture was actually optimal — or just inherited.',
  companyLocation: 'Based in Mount Tremper, NY, the team combines decades of mechanical engineering, thermodynamics, and manufacturing experience to bring the UniMod from concept to commercially viable product.',
  companyQuote: 'We didn\'t set out to build a better engine. We set out to ask whether the engine itself was built right in the first place.',
  teamMembers: [
    { name: 'Paul Borner', role: 'Co-founder & Chief Engineer', initials: 'PB' },
    { name: 'Matthew Borner', role: 'Co-founder & Chief Technology Officer', initials: 'MB' },
  ],
  contactTitle: "Let's talk about what UniMod can do for you",
  contactSubtext: "Whether you're an investor, engineer, or fleet operator — we'd love to hear from you.",
  contactLocation: 'Mount Tremper, NY 12457',
  contactPhone: '(203) 858-1620',
  contactNames: 'Paul & Matthew Borner',
}
