export const investorContent = {
  heroBadge: 'Patented Technology · Raising $24M Series A',
  heroHeadline: 'The $180B Engine Market',
  heroHeadlineAccent: 'Is Ripe for Disruption.',
  heroSubtext: 'Fleet operators spend 40% of operating costs on fuel and maintenance. UniMod cuts both — with a single modular power system that replaces the combustion engine, the drivetrain, and the building generator.',
  heroStats: [
    { value: '$24M', label: 'Raising Now' },
    { value: '$180B', label: 'Total Addressable Market' },
    { value: '40%', label: 'Fuel Cost Reduction' },
    { value: '7', label: 'Working Prototypes Built' },
  ],
  howTitle: 'Why existing solutions fall short',
  howDescription: 'Electric vehicles require massive battery packs that degrade, take hours to charge, and cost $15K+ to replace. Hydrogen infrastructure doesn\'t exist. Diesel is dirty and increasingly regulated. Fleet operators need a bridge technology that works today — with existing fuel infrastructure — while delivering dramatically better economics.',
  howPoints: [
    { title: 'The Problem With EVs for Fleets', description: 'Battery degradation, 4-8 hour charge times, $15K+ replacement costs, and range anxiety make full electrification impractical for trucks, buses, and heavy equipment operating 12+ hours daily.' },
    { title: 'The Problem With Diesel Status Quo', description: 'Tightening EPA regulations, volatile fuel prices, and $8K+ annual maintenance per vehicle are squeezing margins. Fleet operators need a cleaner, cheaper alternative that doesn\'t require new infrastructure.' },
    { title: 'The UniMod Advantage', description: 'Hydraulic hybrid technology delivers regenerative braking without batteries, runs on any available fuel, and reduces maintenance costs by 60% through modular hot-swappable components.' },
  ],
  techTitle: 'Competitive Advantages',
  techSubtitle: 'Six patented innovations that create defensible moats',
  techFeatures: [
    { icon: '⚡', title: 'No Battery Degradation', description: 'Hydraulic accumulators replace lithium batteries for energy recovery. They last the lifetime of the vehicle with zero degradation — saving fleet operators $15K+ per vehicle in battery replacements.' },
    { icon: '🔄', title: 'Instant Energy Recovery', description: '100% of braking energy captured hydraulically and available for immediate reuse. No inverters, no charging wait times, no energy conversion losses.' },
    { icon: '🎚️', title: 'Fuel-Agnostic Platform', description: 'Variable compression ratio enables seamless switching between natural gas, gasoline, and diesel. Operators buy whatever fuel is cheapest today — no infrastructure lock-in.' },
    { icon: '⛽', title: '40% Lower Fuel Costs', description: 'HCCI combustion achieves 42% thermal efficiency vs. 25-30% for conventional engines. That\'s $12K+ in annual fuel savings per commercial vehicle.' },
    { icon: '🏗️', title: 'Modular Hot-Swap', description: 'Standardized modules swap in minutes, not days. A failed unit gets replaced roadside while the vehicle keeps running on remaining modules. Fleet uptime goes from 85% to 98%.' },
    { icon: '🌿', title: 'Regulatory Tailwind', description: 'EPA 2027 and EU Stage VI emissions standards are forcing fleet turnover. UniMod meets next-gen standards today on existing fuels — no infrastructure buildout required.' },
  ],
  appsTitle: 'Two $90B+ markets from one platform',
  appsSubtitle: 'The same core technology addresses both commercial transportation and distributed energy — doubling the addressable market without doubling R&D spend.',
  applications: [
    {
      title: 'Commercial Fleet Vehicles',
      description: 'The 8M+ medium and heavy-duty trucks in the US spend $150B annually on fuel and maintenance. UniMod\'s hydraulic hybrid drivetrain offers a drop-in retrofit and OEM pathway that cuts total cost of ownership by 35% — with a 14-month payback period for fleet operators.',
      tags: ['$90B Market', '8M Vehicles', '14-Mo Payback', '35% TCO Savings'],
    },
    {
      title: 'Distributed Building Power',
      description: 'Commercial buildings spend $190B annually on energy. UniMod provides combined heat and power (CHP) from a single modular unit — electricity, HVAC, and hot water — at 85% total system efficiency vs. 35% for grid electricity. Ideal for hospitals, data centers, and campuses seeking energy independence.',
      tags: ['$90B Market', '85% Efficiency', 'Grid Independence', 'CHP'],
    },
  ],
  companyTitle: '30 years of R&D. 7 prototypes. Ready to scale.',
  companyDescription: 'Paul and Matthew Borner have been developing opposed-piston hydraulic engine technology since 1996. Seven working prototypes have validated the core architecture. Patent 8,671,681 B1 protects the fundamental design. The company is now raising $24M to build the beta production unit and begin the national rollout.',
  companyLocation: 'Headquartered in Mount Tremper, NY, with access to manufacturing partners in the greater New York metropolitan area for beta production scaling.',
  companyQuote: 'We\'ve spent three decades proving this works in the shop. Now it\'s time to prove it works in the market.',
  teamMembers: [
    { name: 'Paul Borner', role: 'Co-founder & Chief Engineer · 30 years in engine R&D', initials: 'PB' },
    { name: 'Matthew Borner', role: 'Co-founder & CTO · Operations & commercialization', initials: 'MB' },
  ],
  contactTitle: 'Interested in the $24M raise?',
  contactSubtext: 'We\'re in active conversations with investors who understand energy infrastructure and fleet economics. Request our pitch deck and financial projections.',
  contactLocation: 'Mount Tremper, NY 12457',
  contactPhone: '(203) 858-1620',
  contactNames: 'Paul & Matthew Borner',
}
